// Code generated by dagger-compiler.  Do not edit.
package com.example.myweatherreporter.db;

import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<DatabaseHandler>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code DatabaseHandler} and its
 * dependencies.
 *
 * Being a {@code Provider<DatabaseHandler>} and handling creation and
 * preparation of object instances.
 */
public final class DatabaseHandler$$InjectAdapter extends Binding<DatabaseHandler>
    implements Provider<DatabaseHandler> {
  private Binding<android.content.Context> context;

  public DatabaseHandler$$InjectAdapter() {
    super("com.example.myweatherreporter.db.DatabaseHandler", "members/com.example.myweatherreporter.db.DatabaseHandler", NOT_SINGLETON, DatabaseHandler.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    context = (Binding<android.content.Context>) linker.requestBinding("android.content.Context", DatabaseHandler.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    getBindings.add(context);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<DatabaseHandler>}.
   */
  @Override
  public DatabaseHandler get() {
    DatabaseHandler result = new DatabaseHandler(context.get());
    return result;
  }

}
