// Code generated by dagger-compiler.  Do not edit.
package com.example.myweatherreporter.beans;

import dagger.internal.Binding;
import javax.inject.Provider;

/**
 * A {@code Binding<City>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Being a {@code Provider<City>} and handling creation and
 * preparation of object instances.
 */
public final class City$$InjectAdapter extends Binding<City>
    implements Provider<City> {

  public City$$InjectAdapter() {
    super("com.example.myweatherreporter.beans.City", "members/com.example.myweatherreporter.beans.City", NOT_SINGLETON, City.class);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<City>}.
   */
  @Override
  public City get() {
    City result = new City();
    return result;
  }

}
