// Code generated by dagger-compiler.  Do not edit.
package com.example.myweatherreporter.beans;

import dagger.internal.Binding;
import javax.inject.Provider;

/**
 * A {@code Binding<CityWeather>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Being a {@code Provider<CityWeather>} and handling creation and
 * preparation of object instances.
 */
public final class CityWeather$$InjectAdapter extends Binding<CityWeather>
    implements Provider<CityWeather> {

  public CityWeather$$InjectAdapter() {
    super("com.example.myweatherreporter.beans.CityWeather", "members/com.example.myweatherreporter.beans.CityWeather", NOT_SINGLETON, CityWeather.class);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<CityWeather>}.
   */
  @Override
  public CityWeather get() {
    CityWeather result = new CityWeather();
    return result;
  }

}
